import 'package:avatar_flow/core/constants/app_constants.dart';
import 'package:avatar_flow/core/constants/app_icons.dart';
import 'package:avatar_flow/core/theme/app_theme_extension.dart';
import 'package:avatar_flow/core/utils/spacing.dart';
import 'package:avatar_flow/features/create_avatar/providers/clone_voice_provider.dart';
import 'package:avatar_flow/widgets/circled_icon_widget.dart';
import 'package:avatar_flow/widgets/custom_button.dart';
import 'package:avatar_flow/widgets/custom_svg.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';

class AgreementPage extends StatelessWidget {
  const AgreementPage();

  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;

    return Padding(
      padding: AppConstants.defaultPaddingHorizental.copyWith(
        bottom: 10.h,
        top: 10.h,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Spacer(),
          Container(
            width: 1.sw,
            padding: AppConstants.defaultAllPadding,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(AppConstants.largeRadius),
              color: Theme.of(context).colorScheme.surface,
            ),
            child: Column(
              children: [
                Spacing.y(2),
                Stack(
                  alignment: Alignment.center,
                  children: [
                    CustomSvg(path: AppIconsSvg.wave),
                    CircledIconWidget(
                      color: context.appColors.primary,
                      icon: Icons.mic,
                    ),
                  ],
                ),
                Spacing.y(2),

                Text(
                  "Clone your voice",
                  style: textTheme.headlineMedium!.copyWith(
                    fontWeight: FontWeight.w500,
                  ),
                ),
                Spacing.y(2),
                Text(
                  "Add personalized voices to your characters by cloning your voice",
                  style: textTheme.bodyMedium!.copyWith(
                    color: Theme.of(
                      context,
                    ).colorScheme.onSurface.withValues(alpha: .6),
                  ),
                  textAlign: TextAlign.center,
                ),
                Spacing.y(2),
                Divider(
                  color: Theme.of(
                    context,
                  ).colorScheme.onSurface.withValues(alpha: .3),
                  thickness: 0.5,
                ),

                Spacing.y(3),

                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Consumer<CloneVoiceProvider>(
                      builder: (context, provider, child) {
                        return Checkbox(
                          materialTapTargetSize:
                              MaterialTapTargetSize.shrinkWrap,
                          value: provider.isAgreed,
                          onChanged: (val) {
                            provider.toggleAgreement(val!);
                          },
                        );
                      },
                    ),
                    Spacing.x(2),
                    Expanded(
                      child: Text(
                        "I accept the terms of recording and using my voice in stories generated by the Sleeping app",
                        style: textTheme.bodyMedium!.copyWith(
                          color: Theme.of(
                            context,
                          ).colorScheme.onSurface.withValues(alpha: .6),
                        ),
                      ),
                    ),
                  ],
                ),
                Spacing.y(4),
                //
                Consumer<CloneVoiceProvider>(
                  builder: (context, value, child) => CustomButton(
                    isDisabled: !value.isAgreed,
                    text: "Next",
                    onPressed: () {
                      value.nextStep();
                    },
                  ),
                ),
              ],
            ),
          ),
          Spacer(),
          CustomButton(
            textColor: Theme.of(context).colorScheme.onSurface,
            buttonColor: context.appColors.lightGrey,
            text: "view sample voices",
            onPressed: () {
              // context.read<CloneVoiceProvider>().nextStep();
              showModalBottomSheet(
                context: context,
                builder: (context) {
                  return SizedBox(
                    height: 200.h,
                    child: Column(children: []),
                  );
                },
              );
            },
          ),
          Spacing.y(1.5),
          TextButton(
            onPressed: () => context.read<CloneVoiceProvider>().nextStep(),
            child: Text(
              "Skip and create",
              style: textTheme.bodyMedium!.copyWith(
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
